### ISSUE TITLE
Crash if redis unavailable

### ISSUE THREAD

**Issue by AlexAkulov** [moira-alert/cache#6]
Moira-cache crashed if redis unavailable

cache.log
```
pid:7034 15:22:47.180903 main.go:102: listening on :2003
pid:7034 15:22:47.182828 pattern.go:52: pattern refresh failed: dial tcp [::1]:6379: getsockopt: connection refused
pid:7034 15:22:48.183367 pattern.go:52: pattern refresh failed: dial tcp [::1]:6379: getsockopt: connection refused
pid:7034 15:22:49.184259 pattern.go:52: pattern refresh failed: dial tcp [::1]:6379: getsockopt: connection refused
pid:7034 15:22:50.184591 pattern.go:52: pattern refresh failed: dial tcp [::1]:6379: getsockopt: connection refused
```
journalctl -f moira-cache
```
May 13 15:22:47 moira-dev systemd[1]: Starting moira-cache - metric stream filtering and caching for Moira...
May 13 15:22:47 moira-dev systemd[1]: Started moira-cache - metric stream filtering and caching for Moira.
May 13 15:22:50 moira-dev cache[7034]: panic: runtime error: invalid memory address or nil pointer dereference
May 13 15:22:50 moira-dev cache[7034]: [signal 0xb code=0x1 addr=0x0 pc=0x51af90]
May 13 15:22:50 moira-dev cache[7034]: goroutine 27 [running]:
May 13 15:22:50 moira-dev cache[7034]: github.com/moira-alert/cache/filter.findPart(0xc820011c00, 0x6, 0x3d, 0xc820033c10, 0x1, 0x1, 0x0, 0x0, 0x0, 0x5340c3)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/filter/pattern.go:160 +0x450
May 13 15:22:50 moira-dev cache[7034]: github.com/moira-alert/cache/filter.(*PatternStorage).MatchPattern(0xc8200b12a0, 0xc820011c00, 0x2b, 0x3d, 0x0, 0x0, 0x0)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/filter/pattern.go:133 +0x1c2
May 13 15:22:50 moira-dev cache[7034]: github.com/moira-alert/cache/filter.(*PatternStorage).ProcessIncomingMetric(0xc8200b12a0, 0xc820011c00, 0x3c, 0x3d, 0x0)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/filter/metric.go:98 +0x80c
May 13 15:22:50 moira-dev cache[7034]: main.handleConnection.func1(0xc8200b18d0, 0xc820011c00, 0x3d, 0x3d, 0xc8200b25a0)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/main.go:200 +0x6c
May 13 15:22:50 moira-dev cache[7034]: created by main.handleConnection
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/main.go:203 +0x33c
May 13 15:22:50 moira-dev cache[7034]: goroutine 1 [chan receive]:
May 13 15:22:50 moira-dev cache[7034]: github.com/rcrowley/goagain.Wait(0x7f2ef2960d50, 0xc820020128, 0x7f2ef2960d50, 0x0, 0x0)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/rcrowley/goagain/goagain.go:207 +0x41a
May 13 15:22:50 moira-dev cache[7034]: main.main()
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/main.go:117 +0x1390
May 13 15:22:50 moira-dev cache[7034]: goroutine 17 [syscall, locked to thread]:
May 13 15:22:50 moira-dev cache[7034]: runtime.goexit()
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
May 13 15:22:50 moira-dev cache[7034]: goroutine 6 [syscall]:
May 13 15:22:50 moira-dev cache[7034]: os/signal.loop()
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
May 13 15:22:50 moira-dev cache[7034]: created by os/signal.init.1
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
May 13 15:22:50 moira-dev cache[7034]: goroutine 7 [chan receive]:
May 13 15:22:50 moira-dev cache[7034]: github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x8252e0)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/rcrowley/go-metrics/meter.go:221 +0x4b
May 13 15:22:50 moira-dev cache[7034]: created by github.com/rcrowley/go-metrics.NewMeter
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/rcrowley/go-metrics/meter.go:40 +0x154
May 13 15:22:50 moira-dev cache[7034]: goroutine 8 [sleep]:
May 13 15:22:50 moira-dev cache[7034]: time.Sleep(0x3b9aca00)
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/runtime/time.go:59 +0xf9
May 13 15:22:50 moira-dev cache[7034]: github.com/moira-alert/cache/filter.(*PatternStorage).Refresh(0xc8200b12a0, 0xc8200b1290)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/filter/pattern.go:55 +0x1b7
May 13 15:22:50 moira-dev cache[7034]: created by main.main
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/main.go:88 +0xe4f
May 13 15:22:50 moira-dev cache[7034]: goroutine 9 [chan receive]:
May 13 15:22:50 moira-dev cache[7034]: github.com/cyberdelia/go-metrics-graphite.GraphiteWithConfig(0xc8200d4150, 0x7f2ef295f358, 0xc82000e6f0, 0xdf8475800, 0x1, 0xc82000bb80, 0x12, 0xc8200d4450, 0x5, 0x5)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/cyberdelia/go-metrics-graphite/graphite.go:43 +0xbd
May 13 15:22:50 moira-dev cache[7034]: github.com/cyberdelia/go-metrics-graphite.Graphite(0x7f2ef295f358, 0xc82000e6f0, 0xdf8475800, 0xc82000bb80, 0x12, 0xc8200d4150)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/cyberdelia/go-metrics-graphite/graphite.go:37 +0x10e
May 13 15:22:50 moira-dev cache[7034]: created by main.main
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/main.go:92 +0xff1
May 13 15:22:50 moira-dev cache[7034]: goroutine 10 [IO wait]:
May 13 15:22:50 moira-dev cache[7034]: net.runtime_pollWait(0x7f2ef2960b80, 0x72, 0xc82000e1f0)
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/runtime/netpoll.go:157 +0x60
May 13 15:22:50 moira-dev cache[7034]: net.(*pollDesc).Wait(0xc8200c81b0, 0x72, 0x0, 0x0)
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
May 13 15:22:50 moira-dev cache[7034]: net.(*pollDesc).WaitRead(0xc8200c81b0, 0x0, 0x0)
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
May 13 15:22:50 moira-dev cache[7034]: net.(*netFD).accept(0xc8200c8150, 0x0, 0x7f2ef2960e30, 0xc8200de200)
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/net/fd_unix.go:408 +0x27c
May 13 15:22:50 moira-dev cache[7034]: net.(*TCPListener).AcceptTCP(0xc820020128, 0xc820031ef8, 0x0, 0x0)
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
May 13 15:22:50 moira-dev cache[7034]: net.(*TCPListener).Accept(0xc820020128, 0x0, 0x0, 0x0, 0x0)
May 13 15:22:50 moira-dev cache[7034]: /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
May 13 15:22:50 moira-dev cache[7034]: main.serve(0x7f2ef2960d50, 0xc820020128, 0xc8200b1770)
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/main.go:167 +0x111
May 13 15:22:50 moira-dev cache[7034]: created by main.main
May 13 15:22:50 moira-dev cache[7034]: /vagrant/project/gocode/src/github.com/moira-alert/cache/main.go:104 +0x1372
May 13 15:22:50 moira-dev cache[7034]: goroutine 11 [select, locked to thread]:
May 13 15:22:50 moira-dev systemd[1]: moira-cache.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 13 15:22:50 moira-dev systemd[1]: Unit moira-cache.service entered failed state.
May 13 15:22:50 moira-dev systemd[1]: moira-cache.service failed.
```

**Comment by gmlexx** [comment]
@28af065 should fix this.
Cache tried to process metrics without initialized pattern storage, because of redis was unavailable.

**Comment by beevee** [comment]
Is it fixed?

**Comment by AlexAkulov** [comment]
yes
